# Generated by Django 4.2.4 on 2023-08-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amazon_authorization',
            field=models.BooleanField(default=False),
        ),
    ]
