# Generated by Django 4.2.4 on 2023-08-28 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('selling_partner_id', models.CharField(max_length=255, null=True)),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_place_id', models.CharField(choices=[('AMEN7PMS3EDWL', 'Belgium'), ('A1805IZSGTT6HS', 'Netherlands'), ('A1PA6795UKMFR9', 'Germany'), ('APJ6JRA9NG5V4', 'Italy'), ('A2NODRKZP88ZB9', 'Sweden'), ('A21TJRUUN4KGV', 'India'), ('A1F83G8C2ARO7P', 'United Kingdom'), ('ATVPDKIKX0DER', 'Sandbox')], default='ATVPDKIKX0DER', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
