# Generated by Django 4.2.4 on 2023-08-29 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercredential', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_credentials',
            options={'verbose_name_plural': 'User Credentials'},
        ),
        migrations.AlterField(
            model_name='user_credentials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cred', to=settings.AUTH_USER_MODEL),
        ),
    ]
